### ISSUE TITLE
enable_wal option

### ISSUE THREAD

**Issue by simonw** [datasette/datasette-load#11]
In some cases users may want to enable WAL on the new database after it is installed into Datasette.

**Comment by simonw** [comment]
```yaml
plugins:
  datasette-load:
    staging_directory: /tmp
    database_directory: /home/location
    enable_wal: true
```
